// source: zk_llm_http_api.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = (function() {
  if (this) { return this; }
  if (typeof window !== 'undefined') { return window; }
  if (typeof global !== 'undefined') { return global; }
  if (typeof self !== 'undefined') { return self; }
  return Function('return this')();
}.call(null));

var google_api_annotations_pb = require('./google/api/annotations_pb.js');
goog.object.extend(proto, google_api_annotations_pb);
goog.exportSymbol('zk_llm_almalgo_labs_zk_llm1.HealthRequest', null, global);
goog.exportSymbol('zk_llm_almalgo_labs_zk_llm1.HealthResponse', null, global);
goog.exportSymbol('zk_llm_almalgo_labs_zk_llm1.LayerRequest', null, global);
goog.exportSymbol('zk_llm_almalgo_labs_zk_llm1.LayerResponse', null, global);
goog.exportSymbol('zk_llm_almalgo_labs_zk_llm1.SessionRequest', null, global);
goog.exportSymbol('zk_llm_almalgo_labs_zk_llm1.SessionResponse', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
zk_llm_almalgo_labs_zk_llm1.HealthRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(zk_llm_almalgo_labs_zk_llm1.HealthRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  zk_llm_almalgo_labs_zk_llm1.HealthRequest.displayName = 'zk_llm_almalgo_labs_zk_llm1.HealthRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
zk_llm_almalgo_labs_zk_llm1.HealthResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(zk_llm_almalgo_labs_zk_llm1.HealthResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  zk_llm_almalgo_labs_zk_llm1.HealthResponse.displayName = 'zk_llm_almalgo_labs_zk_llm1.HealthResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
zk_llm_almalgo_labs_zk_llm1.SessionRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(zk_llm_almalgo_labs_zk_llm1.SessionRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  zk_llm_almalgo_labs_zk_llm1.SessionRequest.displayName = 'zk_llm_almalgo_labs_zk_llm1.SessionRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
zk_llm_almalgo_labs_zk_llm1.SessionResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(zk_llm_almalgo_labs_zk_llm1.SessionResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  zk_llm_almalgo_labs_zk_llm1.SessionResponse.displayName = 'zk_llm_almalgo_labs_zk_llm1.SessionResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
zk_llm_almalgo_labs_zk_llm1.LayerRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, zk_llm_almalgo_labs_zk_llm1.LayerRequest.repeatedFields_, null);
};
goog.inherits(zk_llm_almalgo_labs_zk_llm1.LayerRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  zk_llm_almalgo_labs_zk_llm1.LayerRequest.displayName = 'zk_llm_almalgo_labs_zk_llm1.LayerRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
zk_llm_almalgo_labs_zk_llm1.LayerResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, zk_llm_almalgo_labs_zk_llm1.LayerResponse.repeatedFields_, null);
};
goog.inherits(zk_llm_almalgo_labs_zk_llm1.LayerResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  zk_llm_almalgo_labs_zk_llm1.LayerResponse.displayName = 'zk_llm_almalgo_labs_zk_llm1.LayerResponse';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
zk_llm_almalgo_labs_zk_llm1.HealthRequest.prototype.toObject = function(opt_includeInstance) {
  return zk_llm_almalgo_labs_zk_llm1.HealthRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!zk_llm_almalgo_labs_zk_llm1.HealthRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
zk_llm_almalgo_labs_zk_llm1.HealthRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    op: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!zk_llm_almalgo_labs_zk_llm1.HealthRequest}
 */
zk_llm_almalgo_labs_zk_llm1.HealthRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new zk_llm_almalgo_labs_zk_llm1.HealthRequest;
  return zk_llm_almalgo_labs_zk_llm1.HealthRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!zk_llm_almalgo_labs_zk_llm1.HealthRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!zk_llm_almalgo_labs_zk_llm1.HealthRequest}
 */
zk_llm_almalgo_labs_zk_llm1.HealthRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setOp(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
zk_llm_almalgo_labs_zk_llm1.HealthRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  zk_llm_almalgo_labs_zk_llm1.HealthRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!zk_llm_almalgo_labs_zk_llm1.HealthRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
zk_llm_almalgo_labs_zk_llm1.HealthRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getOp();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string op = 1;
 * @return {string}
 */
zk_llm_almalgo_labs_zk_llm1.HealthRequest.prototype.getOp = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!zk_llm_almalgo_labs_zk_llm1.HealthRequest} returns this
 */
zk_llm_almalgo_labs_zk_llm1.HealthRequest.prototype.setOp = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
zk_llm_almalgo_labs_zk_llm1.HealthResponse.prototype.toObject = function(opt_includeInstance) {
  return zk_llm_almalgo_labs_zk_llm1.HealthResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!zk_llm_almalgo_labs_zk_llm1.HealthResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
zk_llm_almalgo_labs_zk_llm1.HealthResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    status: jspb.Message.getFieldWithDefault(msg, 1, ""),
    service: jspb.Message.getFieldWithDefault(msg, 2, ""),
    model: jspb.Message.getFieldWithDefault(msg, 3, ""),
    modelStatus: jspb.Message.getFieldWithDefault(msg, 4, ""),
    modelError: jspb.Message.getFieldWithDefault(msg, 5, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!zk_llm_almalgo_labs_zk_llm1.HealthResponse}
 */
zk_llm_almalgo_labs_zk_llm1.HealthResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new zk_llm_almalgo_labs_zk_llm1.HealthResponse;
  return zk_llm_almalgo_labs_zk_llm1.HealthResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!zk_llm_almalgo_labs_zk_llm1.HealthResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!zk_llm_almalgo_labs_zk_llm1.HealthResponse}
 */
zk_llm_almalgo_labs_zk_llm1.HealthResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setStatus(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setService(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setModel(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setModelStatus(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setModelError(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
zk_llm_almalgo_labs_zk_llm1.HealthResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  zk_llm_almalgo_labs_zk_llm1.HealthResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!zk_llm_almalgo_labs_zk_llm1.HealthResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
zk_llm_almalgo_labs_zk_llm1.HealthResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getStatus();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getService();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getModel();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getModelStatus();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getModelError();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
};


/**
 * optional string status = 1;
 * @return {string}
 */
zk_llm_almalgo_labs_zk_llm1.HealthResponse.prototype.getStatus = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!zk_llm_almalgo_labs_zk_llm1.HealthResponse} returns this
 */
zk_llm_almalgo_labs_zk_llm1.HealthResponse.prototype.setStatus = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string service = 2;
 * @return {string}
 */
zk_llm_almalgo_labs_zk_llm1.HealthResponse.prototype.getService = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!zk_llm_almalgo_labs_zk_llm1.HealthResponse} returns this
 */
zk_llm_almalgo_labs_zk_llm1.HealthResponse.prototype.setService = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string model = 3;
 * @return {string}
 */
zk_llm_almalgo_labs_zk_llm1.HealthResponse.prototype.getModel = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!zk_llm_almalgo_labs_zk_llm1.HealthResponse} returns this
 */
zk_llm_almalgo_labs_zk_llm1.HealthResponse.prototype.setModel = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string model_status = 4;
 * @return {string}
 */
zk_llm_almalgo_labs_zk_llm1.HealthResponse.prototype.getModelStatus = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!zk_llm_almalgo_labs_zk_llm1.HealthResponse} returns this
 */
zk_llm_almalgo_labs_zk_llm1.HealthResponse.prototype.setModelStatus = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string model_error = 5;
 * @return {string}
 */
zk_llm_almalgo_labs_zk_llm1.HealthResponse.prototype.getModelError = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!zk_llm_almalgo_labs_zk_llm1.HealthResponse} returns this
 */
zk_llm_almalgo_labs_zk_llm1.HealthResponse.prototype.setModelError = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
zk_llm_almalgo_labs_zk_llm1.SessionRequest.prototype.toObject = function(opt_includeInstance) {
  return zk_llm_almalgo_labs_zk_llm1.SessionRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!zk_llm_almalgo_labs_zk_llm1.SessionRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
zk_llm_almalgo_labs_zk_llm1.SessionRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    publicContextB64: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!zk_llm_almalgo_labs_zk_llm1.SessionRequest}
 */
zk_llm_almalgo_labs_zk_llm1.SessionRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new zk_llm_almalgo_labs_zk_llm1.SessionRequest;
  return zk_llm_almalgo_labs_zk_llm1.SessionRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!zk_llm_almalgo_labs_zk_llm1.SessionRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!zk_llm_almalgo_labs_zk_llm1.SessionRequest}
 */
zk_llm_almalgo_labs_zk_llm1.SessionRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setPublicContextB64(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
zk_llm_almalgo_labs_zk_llm1.SessionRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  zk_llm_almalgo_labs_zk_llm1.SessionRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!zk_llm_almalgo_labs_zk_llm1.SessionRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
zk_llm_almalgo_labs_zk_llm1.SessionRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPublicContextB64();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string public_context_b64 = 1;
 * @return {string}
 */
zk_llm_almalgo_labs_zk_llm1.SessionRequest.prototype.getPublicContextB64 = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!zk_llm_almalgo_labs_zk_llm1.SessionRequest} returns this
 */
zk_llm_almalgo_labs_zk_llm1.SessionRequest.prototype.setPublicContextB64 = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
zk_llm_almalgo_labs_zk_llm1.SessionResponse.prototype.toObject = function(opt_includeInstance) {
  return zk_llm_almalgo_labs_zk_llm1.SessionResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!zk_llm_almalgo_labs_zk_llm1.SessionResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
zk_llm_almalgo_labs_zk_llm1.SessionResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    sessionId: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!zk_llm_almalgo_labs_zk_llm1.SessionResponse}
 */
zk_llm_almalgo_labs_zk_llm1.SessionResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new zk_llm_almalgo_labs_zk_llm1.SessionResponse;
  return zk_llm_almalgo_labs_zk_llm1.SessionResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!zk_llm_almalgo_labs_zk_llm1.SessionResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!zk_llm_almalgo_labs_zk_llm1.SessionResponse}
 */
zk_llm_almalgo_labs_zk_llm1.SessionResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setSessionId(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
zk_llm_almalgo_labs_zk_llm1.SessionResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  zk_llm_almalgo_labs_zk_llm1.SessionResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!zk_llm_almalgo_labs_zk_llm1.SessionResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
zk_llm_almalgo_labs_zk_llm1.SessionResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSessionId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string session_id = 1;
 * @return {string}
 */
zk_llm_almalgo_labs_zk_llm1.SessionResponse.prototype.getSessionId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!zk_llm_almalgo_labs_zk_llm1.SessionResponse} returns this
 */
zk_llm_almalgo_labs_zk_llm1.SessionResponse.prototype.setSessionId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
zk_llm_almalgo_labs_zk_llm1.LayerRequest.repeatedFields_ = [4,5,6];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
zk_llm_almalgo_labs_zk_llm1.LayerRequest.prototype.toObject = function(opt_includeInstance) {
  return zk_llm_almalgo_labs_zk_llm1.LayerRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!zk_llm_almalgo_labs_zk_llm1.LayerRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
zk_llm_almalgo_labs_zk_llm1.LayerRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    sessionId: jspb.Message.getFieldWithDefault(msg, 1, ""),
    layerIdx: jspb.Message.getFieldWithDefault(msg, 2, 0),
    operation: jspb.Message.getFieldWithDefault(msg, 3, ""),
    encryptedVectorsB64List: (f = jspb.Message.getRepeatedField(msg, 4)) == null ? undefined : f,
    chunkSizesList: (f = jspb.Message.getRepeatedField(msg, 5)) == null ? undefined : f,
    packCountsList: (f = jspb.Message.getRepeatedField(msg, 6)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!zk_llm_almalgo_labs_zk_llm1.LayerRequest}
 */
zk_llm_almalgo_labs_zk_llm1.LayerRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new zk_llm_almalgo_labs_zk_llm1.LayerRequest;
  return zk_llm_almalgo_labs_zk_llm1.LayerRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!zk_llm_almalgo_labs_zk_llm1.LayerRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!zk_llm_almalgo_labs_zk_llm1.LayerRequest}
 */
zk_llm_almalgo_labs_zk_llm1.LayerRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setSessionId(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setLayerIdx(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setOperation(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.addEncryptedVectorsB64(value);
      break;
    case 5:
      var values = /** @type {!Array<number>} */ (reader.isDelimited() ? reader.readPackedInt32() : [reader.readInt32()]);
      for (var i = 0; i < values.length; i++) {
        msg.addChunkSizes(values[i]);
      }
      break;
    case 6:
      var values = /** @type {!Array<number>} */ (reader.isDelimited() ? reader.readPackedInt32() : [reader.readInt32()]);
      for (var i = 0; i < values.length; i++) {
        msg.addPackCounts(values[i]);
      }
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
zk_llm_almalgo_labs_zk_llm1.LayerRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  zk_llm_almalgo_labs_zk_llm1.LayerRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!zk_llm_almalgo_labs_zk_llm1.LayerRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
zk_llm_almalgo_labs_zk_llm1.LayerRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSessionId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getLayerIdx();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = message.getOperation();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getEncryptedVectorsB64List();
  if (f.length > 0) {
    writer.writeRepeatedString(
      4,
      f
    );
  }
  f = message.getChunkSizesList();
  if (f.length > 0) {
    writer.writePackedInt32(
      5,
      f
    );
  }
  f = message.getPackCountsList();
  if (f.length > 0) {
    writer.writePackedInt32(
      6,
      f
    );
  }
};


/**
 * optional string session_id = 1;
 * @return {string}
 */
zk_llm_almalgo_labs_zk_llm1.LayerRequest.prototype.getSessionId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!zk_llm_almalgo_labs_zk_llm1.LayerRequest} returns this
 */
zk_llm_almalgo_labs_zk_llm1.LayerRequest.prototype.setSessionId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional int32 layer_idx = 2;
 * @return {number}
 */
zk_llm_almalgo_labs_zk_llm1.LayerRequest.prototype.getLayerIdx = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!zk_llm_almalgo_labs_zk_llm1.LayerRequest} returns this
 */
zk_llm_almalgo_labs_zk_llm1.LayerRequest.prototype.setLayerIdx = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional string operation = 3;
 * @return {string}
 */
zk_llm_almalgo_labs_zk_llm1.LayerRequest.prototype.getOperation = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!zk_llm_almalgo_labs_zk_llm1.LayerRequest} returns this
 */
zk_llm_almalgo_labs_zk_llm1.LayerRequest.prototype.setOperation = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * repeated string encrypted_vectors_b64 = 4;
 * @return {!Array<string>}
 */
zk_llm_almalgo_labs_zk_llm1.LayerRequest.prototype.getEncryptedVectorsB64List = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 4));
};


/**
 * @param {!Array<string>} value
 * @return {!zk_llm_almalgo_labs_zk_llm1.LayerRequest} returns this
 */
zk_llm_almalgo_labs_zk_llm1.LayerRequest.prototype.setEncryptedVectorsB64List = function(value) {
  return jspb.Message.setField(this, 4, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!zk_llm_almalgo_labs_zk_llm1.LayerRequest} returns this
 */
zk_llm_almalgo_labs_zk_llm1.LayerRequest.prototype.addEncryptedVectorsB64 = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 4, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!zk_llm_almalgo_labs_zk_llm1.LayerRequest} returns this
 */
zk_llm_almalgo_labs_zk_llm1.LayerRequest.prototype.clearEncryptedVectorsB64List = function() {
  return this.setEncryptedVectorsB64List([]);
};


/**
 * repeated int32 chunk_sizes = 5;
 * @return {!Array<number>}
 */
zk_llm_almalgo_labs_zk_llm1.LayerRequest.prototype.getChunkSizesList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedField(this, 5));
};


/**
 * @param {!Array<number>} value
 * @return {!zk_llm_almalgo_labs_zk_llm1.LayerRequest} returns this
 */
zk_llm_almalgo_labs_zk_llm1.LayerRequest.prototype.setChunkSizesList = function(value) {
  return jspb.Message.setField(this, 5, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 * @return {!zk_llm_almalgo_labs_zk_llm1.LayerRequest} returns this
 */
zk_llm_almalgo_labs_zk_llm1.LayerRequest.prototype.addChunkSizes = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 5, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!zk_llm_almalgo_labs_zk_llm1.LayerRequest} returns this
 */
zk_llm_almalgo_labs_zk_llm1.LayerRequest.prototype.clearChunkSizesList = function() {
  return this.setChunkSizesList([]);
};


/**
 * repeated int32 pack_counts = 6;
 * @return {!Array<number>}
 */
zk_llm_almalgo_labs_zk_llm1.LayerRequest.prototype.getPackCountsList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedField(this, 6));
};


/**
 * @param {!Array<number>} value
 * @return {!zk_llm_almalgo_labs_zk_llm1.LayerRequest} returns this
 */
zk_llm_almalgo_labs_zk_llm1.LayerRequest.prototype.setPackCountsList = function(value) {
  return jspb.Message.setField(this, 6, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 * @return {!zk_llm_almalgo_labs_zk_llm1.LayerRequest} returns this
 */
zk_llm_almalgo_labs_zk_llm1.LayerRequest.prototype.addPackCounts = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 6, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!zk_llm_almalgo_labs_zk_llm1.LayerRequest} returns this
 */
zk_llm_almalgo_labs_zk_llm1.LayerRequest.prototype.clearPackCountsList = function() {
  return this.setPackCountsList([]);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
zk_llm_almalgo_labs_zk_llm1.LayerResponse.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
zk_llm_almalgo_labs_zk_llm1.LayerResponse.prototype.toObject = function(opt_includeInstance) {
  return zk_llm_almalgo_labs_zk_llm1.LayerResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!zk_llm_almalgo_labs_zk_llm1.LayerResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
zk_llm_almalgo_labs_zk_llm1.LayerResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    encryptedResultsB64List: (f = jspb.Message.getRepeatedField(msg, 1)) == null ? undefined : f,
    operation: jspb.Message.getFieldWithDefault(msg, 2, ""),
    layerIdx: jspb.Message.getFieldWithDefault(msg, 3, 0),
    elapsedMs: jspb.Message.getFloatingPointFieldWithDefault(msg, 4, 0.0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!zk_llm_almalgo_labs_zk_llm1.LayerResponse}
 */
zk_llm_almalgo_labs_zk_llm1.LayerResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new zk_llm_almalgo_labs_zk_llm1.LayerResponse;
  return zk_llm_almalgo_labs_zk_llm1.LayerResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!zk_llm_almalgo_labs_zk_llm1.LayerResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!zk_llm_almalgo_labs_zk_llm1.LayerResponse}
 */
zk_llm_almalgo_labs_zk_llm1.LayerResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.addEncryptedResultsB64(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setOperation(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setLayerIdx(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setElapsedMs(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
zk_llm_almalgo_labs_zk_llm1.LayerResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  zk_llm_almalgo_labs_zk_llm1.LayerResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!zk_llm_almalgo_labs_zk_llm1.LayerResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
zk_llm_almalgo_labs_zk_llm1.LayerResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getEncryptedResultsB64List();
  if (f.length > 0) {
    writer.writeRepeatedString(
      1,
      f
    );
  }
  f = message.getOperation();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getLayerIdx();
  if (f !== 0) {
    writer.writeInt32(
      3,
      f
    );
  }
  f = message.getElapsedMs();
  if (f !== 0.0) {
    writer.writeDouble(
      4,
      f
    );
  }
};


/**
 * repeated string encrypted_results_b64 = 1;
 * @return {!Array<string>}
 */
zk_llm_almalgo_labs_zk_llm1.LayerResponse.prototype.getEncryptedResultsB64List = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 1));
};


/**
 * @param {!Array<string>} value
 * @return {!zk_llm_almalgo_labs_zk_llm1.LayerResponse} returns this
 */
zk_llm_almalgo_labs_zk_llm1.LayerResponse.prototype.setEncryptedResultsB64List = function(value) {
  return jspb.Message.setField(this, 1, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!zk_llm_almalgo_labs_zk_llm1.LayerResponse} returns this
 */
zk_llm_almalgo_labs_zk_llm1.LayerResponse.prototype.addEncryptedResultsB64 = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 1, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!zk_llm_almalgo_labs_zk_llm1.LayerResponse} returns this
 */
zk_llm_almalgo_labs_zk_llm1.LayerResponse.prototype.clearEncryptedResultsB64List = function() {
  return this.setEncryptedResultsB64List([]);
};


/**
 * optional string operation = 2;
 * @return {string}
 */
zk_llm_almalgo_labs_zk_llm1.LayerResponse.prototype.getOperation = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!zk_llm_almalgo_labs_zk_llm1.LayerResponse} returns this
 */
zk_llm_almalgo_labs_zk_llm1.LayerResponse.prototype.setOperation = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional int32 layer_idx = 3;
 * @return {number}
 */
zk_llm_almalgo_labs_zk_llm1.LayerResponse.prototype.getLayerIdx = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!zk_llm_almalgo_labs_zk_llm1.LayerResponse} returns this
 */
zk_llm_almalgo_labs_zk_llm1.LayerResponse.prototype.setLayerIdx = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional double elapsed_ms = 4;
 * @return {number}
 */
zk_llm_almalgo_labs_zk_llm1.LayerResponse.prototype.getElapsedMs = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 4, 0.0));
};


/**
 * @param {number} value
 * @return {!zk_llm_almalgo_labs_zk_llm1.LayerResponse} returns this
 */
zk_llm_almalgo_labs_zk_llm1.LayerResponse.prototype.setElapsedMs = function(value) {
  return jspb.Message.setProto3FloatField(this, 4, value);
};


goog.object.extend(exports, zk_llm_almalgo_labs_zk_llm1);
